In [1]:
import numpy as np
import scipy.io as sio
import pandas as pd

In [2]:
df = sio.loadmat('./data/yahoo/yahoo-33.mat')
df

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Fri Jan 12 10:55:34 2018',
 '__version__': '1.0',
 '__globals__': [],
 'Y': array([[0.        ],
        [0.01396449],
        [0.39248387],
        ...,
        [0.60367285],
        [0.62716728],
        [0.67036502]]),
 'L': array([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]], dtype=int64)}

In [3]:
print(df['L'])

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [4]:
df2 = pd.DataFrame(df['L'])
df2

0
0     0
1     0
2     0
3     0
4     0
...  ..
1422  0
1423  0
1424  0
1425  0
1426  0

[1427 rows x 1 columns]

In [5]:
df2.nunique()

0    2
dtype: int64

In [6]:
df2.nunique().value_counts()

2    1
dtype: int64

In [7]:
df2[0].unique()

array([0, 1], dtype=int64)

In [9]:
df2.apply(lambda col: ', '.join(map(str, col.unique())))

0    0, 1
dtype: object

In [11]:
df2[0].value_counts()

0    1420
1       7
Name: 0, dtype: int64

In [12]:
df3 = df['Y']

In [13]:
df3.shape

(1427, 1)

In [14]:
df2.shape

(1427, 1)

In [20]:
L = np.zeros(df2.shape[0],dtype='float')
L

array([0., 0., 0., ..., 0., 0., 0.])

In [16]:
L.shape

(1427,)

In [17]:
df

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Fri Jan 12 10:55:34 2018',
 '__version__': '1.0',
 '__globals__': [],
 'Y': array([[0.        ],
        [0.01396449],
        [0.39248387],
        ...,
        [0.60367285],
        [0.62716728],
        [0.67036502]]),
 'L': array([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]], dtype=int64)}

In [18]:
Y = df['Y']

In [19]:
Y_mean = np.mean(Y)
Y_std = np.std(Y)
print(Y_mean, Y_std)

0.39806677281186553 0.1516485043539443


In [21]:
Y = (Y-Y_mean)/Y_std
Y

array([[-2.62493042],
       [-2.53284584],
       [-0.03681475],
       ...,
       [ 1.35580684],
       [ 1.5107337 ],
       [ 1.79558811]])

In [24]:
L = df['L']
L

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [28]:
def diff(ld):
    L = np.zeros((ld.shape[0],1))
    for i in range(1,ld.shape[0]):
        if(ld[i] != ld[i-1]):
            L[i] = 1;
    return L

In [29]:
L = diff(L)
L

AttributeError: 'function' object has no attribute 'shape'