In [2]:
import numpy as np
import scipy.io as sio
import pandas as pd

In [3]:
df = sio.loadmat('./data/yahoo/yahoo-33.mat')
df

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Fri Jan 12 10:55:34 2018',
 '__version__': '1.0',
 '__globals__': [],
 'Y': array([[0.        ],
        [0.01396449],
        [0.39248387],
        ...,
        [0.60367285],
        [0.62716728],
        [0.67036502]]),
 'L': array([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]])}

In [4]:
print(df['L'])

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [5]:
df2 = pd.DataFrame(df['L'])
df2

0
0     0
1     0
2     0
3     0
4     0
...  ..
1422  0
1423  0
1424  0
1425  0
1426  0

[1427 rows x 1 columns]

In [6]:
df2.nunique()

0    2
dtype: int64

In [7]:
df2.nunique().value_counts()

2    1
dtype: int64

In [8]:
df2[0].unique()

array([0, 1])

In [9]:
df2.apply(lambda col: ', '.join(map(str, col.unique())))

0    0, 1
dtype: object

In [10]:
df2[0].value_counts()

0    1420
1       7
Name: 0, dtype: int64

In [11]:
df3 = df['Y']

In [12]:
df3.shape

(1427, 1)

In [13]:
df2.shape

(1427, 1)

In [14]:
L = np.zeros(df2.shape[0],dtype='float')
L

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
L.shape

(1427,)

In [16]:
df

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Fri Jan 12 10:55:34 2018',
 '__version__': '1.0',
 '__globals__': [],
 'Y': array([[0.        ],
        [0.01396449],
        [0.39248387],
        ...,
        [0.60367285],
        [0.62716728],
        [0.67036502]]),
 'L': array([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]])}

In [17]:
Y = df['Y']

In [18]:
Y_mean = np.mean(Y)
Y_std = np.std(Y)
print(Y_mean, Y_std)

0.39806677281186553 0.1516485043539443


In [19]:
Y = (Y-Y_mean)/Y_std
Y

array([[-2.62493042],
       [-2.53284584],
       [-0.03681475],
       ...,
       [ 1.35580684],
       [ 1.5107337 ],
       [ 1.79558811]])

In [40]:
Y.shape

(1427, 1)

In [20]:
L = df['L']
L

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [21]:
def diff(ld):
    L = np.zeros((ld.shape[0],1))
    for i in range(1,ld.shape[0]):
        if(ld[i] != ld[i-1]):
            L[i] = 1;
    return L

In [24]:
L.shape[0]

1427

In [23]:
L = diff(L)
L

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [36]:
L.value_counts()

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [29]:
df3.shape

(1427, 1)

In [35]:
yx = pd.DataFrame(df['Y'])
yx

0
0     0.000000
1     0.013964
2     0.392484
3     0.500252
4     0.533920
...        ...
1422  0.593430
1423  0.630106
1424  0.603673
1425  0.627167
1426  0.670365

[1427 rows x 1 columns]

In [37]:
yx.nunique()

0    1384
dtype: int64

In [39]:
print(yx.to_string())

             0
0     0.000000
1     0.013964
2     0.392484
3     0.500252
4     0.533920
5     0.544180
6     0.525729
7     0.521573
8     0.535642
9     0.521608
10    0.496026
11    0.460759
12    0.458080
13    0.418291
14    0.453750
15    0.493418
16    0.467715
17    0.378798
18    0.335565
19    0.246961
20    0.226649
21    0.215710
22    0.201711
23    0.196859
24    0.202216
25    0.248022
26    0.303149
27    0.398136
28    0.431664
29    0.442220
30    0.436916
31    0.416483
32    0.366555
33    0.417335
34    0.404414
35    0.385441
36    0.371928
37    0.388484
38    0.386728
39    0.406101
40    0.405857
41    0.321931
42    0.299324
43    0.242492
44    0.226875
45    0.198859
46    0.210406
47    0.202076
48    0.182964
49    0.213224
50    0.272316
51    0.346086
52    0.398171
53    0.469141
54    0.461611
55    0.481575
56    0.443055
57    0.466480
58    0.485575
59    0.491331
60    0.519625
61    0.524199
62    0.576126
63    0.584109
64    0.655514
65    0.42